backend:
  name: github
  repo: wmxmusic/wmxmusic.github.io
  branch: master

media_folder: static/images
public_folder: /images

locale: zh_Hans

collections:
  - name: works
    label: 作品
    folder: content/works/
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 日期, name: date, widget: datetime }
      - { label: 正文, name: body, widget: markdown }

  - name: pages
    label: 页面
    files:
      - label: 首页
        name: index
        file: content/_index.md
        fields:
          - { label: 标题, name: title, widget: string }
          - { label: 正文, name: body, widget: markdown }
      - label: 关于
        name: about
        file: content/about.md
        fields:
          - { label: 标题, name: title, widget: string }
          - { label: 正文, name: body, widget: markdown }
